development:
  secret_key_base: 02e14566ef9761f0fb0f6ecbfac9725c786e7d6f47f1bb9d06acd43ce0e07a6a509d14571330088fd2e2e8d86ff72d0626571443a41988a487a413be1355f9c4

test:
  secret_key_base: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
